export const investmentOptions = {
  stocks: [
    { value: "AAPL", label: "Apple Inc. (AAPL)" },
    { value: "MSFT", label: "Microsoft Corp. (MSFT)" },
    { value: "GOOGL", label: "Alphabet Inc. (GOOGL)" },
    { value: "AMZN", label: "Amazon.com Inc. (AMZN)" },
    { value: "TSLA", label: "Tesla Inc. (TSLA)" },
    { value: "META", label: "Meta Platforms Inc. (META)" },
    { value: "NFLX", label: "Netflix Inc. (NFLX)" },
    { value: "NVDA", label: "NVIDIA Corp. (NVDA)" },
    { value: "AMD", label: "Advanced Micro Devices (AMD)" },
    { value: "INTC", label: "Intel Corp. (INTC)" },
    { value: "BA", label: "Boeing Co. (BA)" },
    { value: "DIS", label: "Walt Disney Co. (DIS)" },
    { value: "V", label: "Visa Inc. (V)" },
    { value: "MA", label: "Mastercard Inc. (MA)" },
    { value: "JPM", label: "JPMorgan Chase & Co. (JPM)" },
    { value: "GS", label: "Goldman Sachs Group (GS)" },
    { value: "WMT", label: "Walmart Inc. (WMT)" },
    { value: "KO", label: "Coca-Cola Co. (KO)" },
    { value: "PEP", label: "PepsiCo Inc. (PEP)" },
    { value: "MCD", label: "McDonald's Corp. (MCD)" },
  ],
  bonds: [
    { value: "US10Y", label: "U.S. 10-Year Treasury Note (US10Y)" },
    { value: "US30Y", label: "U.S. 30-Year Treasury Bond (US30Y)" },
    { value: "US5Y", label: "U.S. 5-Year Treasury Note (US5Y)" },
    { value: "US2Y", label: "U.S. 2-Year Treasury Note (US2Y)" },
    { value: "TIPS10Y", label: "10-Year TIPS (TIPS10Y)" },
    { value: "GER10Y", label: "German 10-Year Bund (GER10Y)" },
    { value: "UKGILT10Y", label: "UK 10-Year Gilt (UKGILT10Y)" },
    { value: "JP10Y", label: "Japan 10-Year JGB (JP10Y)" },
    { value: "FR10Y", label: "France 10-Year OAT (FR10Y)" },
    { value: "CAN10Y", label: "Canada 10-Year Bond (CAN10Y)" },
    { value: "AUS10Y", label: "Australia 10-Year Bond (AUS10Y)" },
    { value: "CH10Y", label: "China 10-Year Bond (CH10Y)" },
    { value: "BR10Y", label: "Brazil 10-Year Bond (BR10Y)" },
    { value: "IN10Y", label: "India 10-Year Bond (IN10Y)" },
    { value: "RU10Y", label: "Russia 10-Year Bond (RU10Y)" },
    { value: "ZA10Y", label: "South Africa 10-Year Bond (ZA10Y)" },
    { value: "MX10Y", label: "Mexico 10-Year Bond (MX10Y)" },
    { value: "IT10Y", label: "Italy 10-Year BTP (IT10Y)" },
    { value: "ES10Y", label: "Spain 10-Year Bond (ES10Y)" },
    { value: "KR10Y", label: "Korea 10-Year Bond (KR10Y)" },
  ],
  crypto: [
    { value: "BTC", label: "Bitcoin (BTC)" },
    { value: "ETH", label: "Ethereum (ETH)" },
    { value: "BNB", label: "Binance Coin (BNB)" },
    { value: "XRP", label: "Ripple (XRP)" },
    { value: "ADA", label: "Cardano (ADA)" },
    { value: "SOL", label: "Solana (SOL)" },
    { value: "DOGE", label: "Dogecoin (DOGE)" },
    { value: "DOT", label: "Polkadot (DOT)" },
    { value: "MATIC", label: "Polygon (MATIC)" },
    { value: "AVAX", label: "Avalanche (AVAX)" },
    { value: "TRX", label: "TRON (TRX)" },
    { value: "LTC", label: "Litecoin (LTC)" },
    { value: "SHIB", label: "Shiba Inu (SHIB)" },
    { value: "UNI", label: "Uniswap (UNI)" },
    { value: "ATOM", label: "Cosmos (ATOM)" },
    { value: "XLM", label: "Stellar (XLM)" },
    { value: "ETC", label: "Ethereum Classic (ETC)" },
    { value: "FIL", label: "Filecoin (FIL)" },
    { value: "ICP", label: "Internet Computer (ICP)" },
    { value: "NEAR", label: "NEAR Protocol (NEAR)" },
  ],
};
